// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: asdr_lex.flex


@SuppressWarnings("fallthrough")
class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\126\u0100\1\u2600\1\u0100\1\u2700"+
    "\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\53\u0100\1\u2d00\10\u2e00"+
    "\31\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00\1\u4f00\1\u5000\1\u5100"+
    "\3\u0100\1\u5200\1\u5300\1\u5400\11\u1f00\1\u5500\4\u0100\1\u5600"+
    "\17\u1f00\2\u0100\1\u5700\41\u1f00\2\u0100\1\u5800\1\u5900\2\u1f00"+
    "\1\u5a00\1\u5b00\27\u0100\1\u5c00\4\u0100\1\u5d00\1\u5e00\41\u1f00"+
    "\1\u5f00\1\u0100\1\u6000\1\u6100\11\u1f00\1\u6200\22\u1f00\1\u6300"+
    "\1\u1f00\1\u6400\1\u6500\1\u1f00\1\u6600\1\u6700\1\u6800\1\u6900"+
    "\2\u1f00\1\u6a00\4\u1f00\1\u6b00\1\u6c00\1\u6d00\1\u6e00\1\u1f00"+
    "\1\u6f00\2\u1f00\1\u7000\1\u7100\1\u7200\2\u1f00\1\u7300\1\u1f00"+
    "\1\u7400\14\u1f00\1\u7500\4\u1f00\246\u0100\1\u7600\20\u0100\1\u7700"+
    "\1\u7800\25\u0100\1\u7900\34\u0100\1\u7a00\14\u1f00\2\u0100\1\u7b00"+
    "\5\u1f00\23\u0100\1\u7c00\17\u0100\1\u7d00\u0adc\u1f00\1\u7e00\1\u7f00"+
    "\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\2\2\2\3\1\2\16\0\4\4\1\2"+
    "\3\4\1\5\3\4\2\6\1\7\1\6\1\4\1\7"+
    "\1\10\1\7\12\11\1\4\1\6\1\12\1\13\3\4"+
    "\1\14\1\15\1\16\1\15\1\17\1\20\7\15\1\21"+
    "\1\22\2\15\1\23\1\15\1\24\6\15\4\4\1\25"+
    "\1\4\3\15\1\26\1\27\1\30\1\15\1\31\1\32"+
    "\2\15\1\33\1\15\1\34\1\35\1\36\1\15\1\37"+
    "\1\40\1\41\1\42\1\15\1\43\3\15\1\6\1\4"+
    "\1\6\1\4\6\0\1\44\32\0\2\4\4\15\4\4"+
    "\1\15\2\4\1\0\7\4\1\15\4\4\1\15\5\4"+
    "\27\15\1\4\37\15\1\4\u01ca\15\4\4\14\15\16\4"+
    "\5\15\7\4\1\15\1\4\1\15\21\4\160\0\5\15"+
    "\1\4\2\15\2\4\4\15\1\4\1\15\6\4\1\15"+
    "\1\4\3\15\1\4\1\15\1\4\24\15\1\4\123\15"+
    "\1\4\213\15\1\4\5\0\2\4\246\15\1\4\46\15"+
    "\2\4\1\15\6\4\51\15\6\4\1\15\1\4\55\0"+
    "\1\4\1\0\1\4\2\0\1\4\2\0\1\4\1\0"+
    "\10\4\33\15\4\4\4\15\15\4\6\0\5\4\1\15"+
    "\4\4\13\0\1\4\1\0\3\4\53\15\37\0\4\4"+
    "\2\15\1\0\143\15\1\4\1\15\10\0\1\4\6\0"+
    "\2\15\2\0\1\4\4\0\2\15\12\0\3\15\2\4"+
    "\1\15\17\4\1\0\1\15\1\0\36\15\33\0\2\4"+
    "\131\15\13\0\1\15\16\4\12\0\41\15\11\0\2\15"+
    "\4\4\1\15\2\4\1\0\30\15\4\0\1\15\11\0"+
    "\1\15\3\0\1\15\5\0\22\4\31\15\3\0\4\4"+
    "\13\15\5\4\30\15\1\4\6\15\1\4\2\0\6\4"+
    "\10\0\52\15\72\0\66\15\3\0\1\15\22\0\1\15"+
    "\7\0\12\15\2\0\2\4\12\0\1\4\20\15\3\0"+
    "\1\4\10\15\2\4\2\15\2\4\26\15\1\4\7\15"+
    "\1\4\1\15\3\4\4\15\2\4\1\0\1\15\7\0"+
    "\2\4\2\0\2\4\3\0\1\15\10\4\1\0\4\4"+
    "\2\15\1\4\3\15\2\0\2\4\12\0\4\15\7\4"+
    "\2\15\1\4\1\0\2\4\3\0\1\4\6\15\4\4"+
    "\2\15\2\4\26\15\1\4\7\15\1\4\2\15\1\4"+
    "\2\15\1\4\2\15\2\4\1\0\1\4\5\0\4\4"+
    "\2\0\2\4\3\0\3\4\1\0\7\4\4\15\1\4"+
    "\1\15\7\4\14\0\3\15\1\0\13\4\3\0\1\4"+
    "\11\15\1\4\3\15\1\4\26\15\1\4\7\15\1\4"+
    "\2\15\1\4\5\15\2\4\1\0\1\15\10\0\1\4"+
    "\3\0\1\4\3\0\2\4\1\15\17\4\2\15\2\0"+
    "\2\4\12\0\1\4\1\15\7\4\1\15\6\0\1\4"+
    "\3\0\1\4\10\15\2\4\2\15\2\4\26\15\1\4"+
    "\7\15\1\4\2\15\1\4\5\15\2\4\1\0\1\15"+
    "\7\0\2\4\2\0\2\4\3\0\7\4\3\0\4\4"+
    "\2\15\1\4\3\15\2\0\2\4\12\0\1\4\1\15"+
    "\20\4\1\0\1\15\1\4\6\15\3\4\3\15\1\4"+
    "\4\15\3\4\2\15\1\4\1\15\1\4\2\15\3\4"+
    "\2\15\3\4\3\15\3\4\14\15\4\4\5\0\3\4"+
    "\3\0\1\4\4\0\2\4\1\15\6\4\1\0\16\4"+
    "\12\0\11\4\1\15\6\4\5\0\10\15\1\4\3\15"+
    "\1\4\27\15\1\4\20\15\2\4\1\0\1\15\7\0"+
    "\1\4\3\0\1\4\4\0\7\4\2\0\1\4\3\15"+
    "\2\4\1\15\2\4\2\15\2\0\2\4\12\0\20\4"+
    "\1\15\3\0\1\4\10\15\1\4\3\15\1\4\27\15"+
    "\1\4\12\15\1\4\5\15\2\4\1\0\1\15\7\0"+
    "\1\4\3\0\1\4\4\0\7\4\2\0\6\4\2\15"+
    "\1\4\2\15\2\0\2\4\12\0\1\4\2\15\1\0"+
    "\14\4\4\0\11\15\1\4\3\15\1\4\51\15\2\0"+
    "\1\15\7\0\1\4\3\0\1\4\4\0\1\15\5\4"+
    "\3\15\1\0\7\4\3\15\2\0\2\4\12\0\12\4"+
    "\6\15\1\4\3\0\1\4\22\15\3\4\30\15\1\4"+
    "\11\15\1\4\1\15\2\4\7\15\3\4\1\0\4\4"+
    "\6\0\1\4\1\0\1\4\10\0\6\4\12\0\2\4"+
    "\2\0\15\4\60\15\1\0\2\15\7\0\4\4\10\15"+
    "\10\0\1\4\12\0\47\4\2\15\1\4\1\15\1\4"+
    "\5\15\1\4\30\15\1\4\1\15\1\4\12\15\1\0"+
    "\2\15\11\0\1\15\2\4\5\15\1\4\1\15\1\4"+
    "\7\0\1\4\12\0\2\4\4\15\40\4\1\15\27\4"+
    "\2\0\6\4\12\0\13\4\1\0\1\4\1\0\1\4"+
    "\1\0\4\4\2\0\10\15\1\4\44\15\4\4\24\0"+
    "\1\4\2\0\5\15\13\0\1\4\44\0\11\4\1\0"+
    "\71\4\53\15\24\0\1\15\12\0\6\4\6\15\4\0"+
    "\4\15\3\0\1\15\3\0\2\15\7\0\3\15\4\0"+
    "\15\15\14\0\1\15\17\0\2\4\46\15\1\4\1\15"+
    "\5\4\1\15\2\4\53\15\1\4\115\15\1\4\4\15"+
    "\2\4\7\15\1\4\1\15\1\4\4\15\2\4\51\15"+
    "\1\4\4\15\2\4\41\15\1\4\4\15\2\4\7\15"+
    "\1\4\1\15\1\4\4\15\2\4\17\15\1\4\71\15"+
    "\1\4\4\15\2\4\103\15\2\4\3\0\40\4\20\15"+
    "\20\4\126\15\2\4\6\15\3\4\u016c\15\2\4\21\15"+
    "\1\4\32\15\5\4\113\15\3\4\13\15\7\4\22\15"+
    "\4\0\11\4\23\15\3\0\13\4\22\15\2\0\14\4"+
    "\15\15\1\4\3\15\1\4\2\0\14\4\64\15\40\0"+
    "\3\4\1\15\3\4\2\15\1\0\2\4\12\0\41\4"+
    "\17\0\6\4\131\15\7\4\5\15\2\0\42\15\1\0"+
    "\1\15\5\4\106\15\12\4\37\15\1\4\14\0\4\4"+
    "\14\0\12\4\12\0\36\15\2\4\5\15\13\4\54\15"+
    "\4\4\32\15\6\4\12\0\46\4\27\15\5\0\4\4"+
    "\65\15\12\0\1\4\35\0\2\4\13\0\6\4\12\0"+
    "\15\4\1\15\10\4\16\0\1\4\20\0\61\4\5\0"+
    "\57\15\21\0\10\15\3\4\12\0\21\4\11\0\14\4"+
    "\3\0\36\15\15\0\2\15\12\0\54\15\16\0\14\4"+
    "\44\15\24\0\10\4\12\0\3\4\3\15\12\0\44\15"+
    "\2\4\11\15\7\4\53\15\2\4\3\15\20\4\3\0"+
    "\1\4\25\0\4\15\1\0\6\15\1\0\2\15\3\0"+
    "\1\15\5\4\300\15\100\0\26\15\2\4\6\15\2\4"+
    "\46\15\2\4\6\15\2\4\10\15\1\4\1\15\1\4"+
    "\1\15\1\4\1\15\1\4\37\15\2\4\65\15\1\4"+
    "\7\15\1\4\1\15\3\4\3\15\1\4\7\15\3\4"+
    "\4\15\2\4\6\15\4\4\15\15\5\4\3\15\1\4"+
    "\7\15\16\4\5\0\30\4\2\3\5\0\20\4\2\15"+
    "\23\4\1\15\13\4\5\0\1\4\12\0\1\4\1\15"+
    "\15\4\1\15\20\4\15\15\3\4\41\15\17\4\15\0"+
    "\4\4\1\0\3\4\14\0\21\4\1\15\4\4\1\15"+
    "\2\4\12\15\1\4\1\15\3\4\5\15\6\4\1\15"+
    "\1\4\1\15\1\4\1\15\1\4\4\15\1\4\13\15"+
    "\2\4\4\15\5\4\5\15\4\4\1\15\21\4\51\15"+
    "\u0177\4\345\15\6\4\4\15\3\0\2\15\14\4\46\15"+
    "\1\4\1\15\5\4\1\15\2\4\70\15\7\4\1\15"+
    "\17\4\1\0\27\15\11\4\7\15\1\4\7\15\1\4"+
    "\7\15\1\4\7\15\1\4\7\15\1\4\7\15\1\4"+
    "\7\15\1\4\7\15\1\4\40\0\57\4\1\15\325\4"+
    "\3\15\31\4\11\15\6\0\1\4\5\15\2\4\5\15"+
    "\4\4\126\15\2\4\2\0\2\4\3\15\1\4\132\15"+
    "\1\4\4\15\5\4\53\15\1\4\136\15\21\4\40\15"+
    "\60\4\320\15\100\4\215\15\103\4\56\15\2\4\15\15"+
    "\3\4\20\15\12\0\2\15\24\4\57\15\1\0\4\4"+
    "\12\0\1\4\37\15\2\0\120\15\2\0\45\4\11\15"+
    "\2\4\147\15\2\4\100\15\5\4\2\15\1\4\1\15"+
    "\1\4\5\15\30\4\20\15\1\0\3\15\1\0\4\15"+
    "\1\0\27\15\5\0\4\4\1\0\13\4\1\15\7\4"+
    "\64\15\14\4\2\0\62\15\22\0\12\4\12\0\6\4"+
    "\22\0\6\15\3\4\1\15\1\4\2\15\13\0\34\15"+
    "\10\0\2\4\27\15\15\0\14\4\35\15\3\4\4\0"+
    "\57\15\16\0\16\4\1\15\12\0\6\4\5\15\1\0"+
    "\12\15\12\0\5\15\1\4\51\15\16\0\11\4\3\15"+
    "\1\0\10\15\2\0\2\4\12\0\6\4\27\15\3\4"+
    "\1\15\3\0\62\15\1\0\1\15\3\0\2\15\2\0"+
    "\5\15\2\0\1\15\1\0\1\15\30\4\3\15\2\4"+
    "\13\15\5\0\2\4\3\15\2\0\12\4\6\15\2\4"+
    "\6\15\2\4\6\15\11\4\7\15\1\4\7\15\1\4"+
    "\53\15\1\4\16\15\6\4\163\15\10\0\1\4\2\0"+
    "\2\4\12\0\6\4\244\15\14\4\27\15\4\4\61\15"+
    "\4\4\u0100\3\156\15\2\4\152\15\46\4\7\15\14\4"+
    "\5\15\5\4\1\15\1\0\12\15\1\4\15\15\1\4"+
    "\5\15\1\4\1\15\1\4\2\15\1\4\2\15\1\4"+
    "\154\15\41\4\153\15\22\4\100\15\2\4\66\15\50\4"+
    "\15\15\3\4\20\0\20\4\20\0\3\4\2\15\30\4"+
    "\3\15\31\4\1\15\6\4\5\15\1\4\207\15\2\4"+
    "\1\0\4\4\1\15\13\4\12\0\7\4\32\15\4\4"+
    "\1\15\1\4\32\15\13\4\131\15\3\4\6\15\2\4"+
    "\6\15\2\4\6\15\2\4\3\15\3\4\2\15\3\4"+
    "\2\15\22\4\3\0\4\4\14\15\1\4\32\15\1\4"+
    "\23\15\1\4\2\15\1\4\17\15\2\4\16\15\42\4"+
    "\173\15\105\4\65\15\210\4\1\0\202\4\35\15\3\4"+
    "\61\15\17\4\1\0\37\4\40\15\15\4\36\15\5\4"+
    "\46\15\5\0\5\4\36\15\2\4\44\15\4\4\10\15"+
    "\1\4\5\15\52\4\236\15\2\4\12\0\6\4\44\15"+
    "\4\4\44\15\4\4\50\15\10\4\64\15\14\4\13\15"+
    "\1\4\17\15\1\4\7\15\1\4\2\15\1\4\13\15"+
    "\1\4\17\15\1\4\7\15\1\4\2\15\103\4\67\15"+
    "\11\4\26\15\12\4\10\15\30\4\6\15\1\4\52\15"+
    "\1\4\11\15\105\4\6\15\2\4\1\15\1\4\54\15"+
    "\1\4\2\15\3\4\1\15\2\4\27\15\12\4\27\15"+
    "\11\4\37\15\101\4\23\15\1\4\2\15\12\4\26\15"+
    "\12\4\32\15\106\4\70\15\6\4\2\15\100\4\1\15"+
    "\3\0\1\4\2\0\5\4\4\0\4\15\1\4\3\15"+
    "\1\4\35\15\2\4\3\0\4\4\1\0\40\4\35\15"+
    "\3\4\35\15\43\4\10\15\1\4\34\15\2\0\31\4"+
    "\66\15\12\4\26\15\12\4\23\15\15\4\22\15\156\4"+
    "\111\15\67\4\63\15\15\4\63\15\15\4\44\15\4\0"+
    "\10\4\12\0\u0146\4\52\15\1\4\2\0\3\4\2\15"+
    "\113\4\3\0\35\15\12\4\1\15\10\4\26\15\13\0"+
    "\37\4\22\15\4\0\52\4\25\15\33\4\27\15\11\4"+
    "\3\0\65\15\17\0\37\4\13\0\2\15\2\0\1\15"+
    "\11\4\4\0\55\15\13\0\2\4\1\0\4\4\1\0"+
    "\12\4\1\0\2\4\31\15\7\4\12\0\6\4\3\0"+
    "\44\15\16\0\1\4\12\0\4\4\1\15\2\0\1\15"+
    "\10\4\43\15\1\0\2\4\1\15\11\4\3\0\60\15"+
    "\16\0\4\15\4\4\4\0\1\4\14\0\1\15\1\4"+
    "\1\15\43\4\22\15\1\4\31\15\14\0\6\4\1\0"+
    "\2\15\1\0\76\4\7\15\1\4\1\15\1\4\4\15"+
    "\1\4\17\15\1\4\12\15\7\4\57\15\14\0\5\4"+
    "\12\0\6\4\4\0\1\4\10\15\2\4\2\15\2\4"+
    "\26\15\1\4\7\15\1\4\2\15\1\4\5\15\1\4"+
    "\2\0\1\15\7\0\2\4\2\0\2\4\3\0\2\4"+
    "\1\15\6\4\1\0\5\4\5\15\2\0\2\4\7\0"+
    "\3\4\5\0\213\4\65\15\22\0\4\15\5\4\12\0"+
    "\4\4\1\0\3\15\36\4\60\15\24\0\2\15\1\4"+
    "\1\15\10\4\12\0\246\4\57\15\7\0\2\4\11\0"+
    "\27\4\4\15\2\0\42\4\60\15\21\0\3\4\1\15"+
    "\13\4\12\0\46\4\53\15\15\0\1\15\7\4\12\0"+
    "\66\4\33\15\2\4\17\0\4\4\12\0\6\4\7\15"+
    "\271\4\54\15\17\0\145\4\100\15\12\0\25\4\10\15"+
    "\2\4\1\15\2\4\10\15\1\4\2\15\1\4\30\15"+
    "\6\0\1\4\2\0\2\4\4\0\1\15\1\0\1\15"+
    "\2\0\14\4\12\0\106\4\10\15\2\4\47\15\7\0"+
    "\2\4\7\0\1\15\1\4\1\15\1\0\33\4\1\15"+
    "\12\0\50\15\7\0\1\15\4\0\10\4\1\0\10\4"+
    "\1\15\13\0\56\15\20\0\3\4\1\15\22\4\111\15"+
    "\7\4\11\15\1\4\45\15\10\0\1\4\10\0\1\15"+
    "\17\4\12\0\30\4\36\15\2\4\26\0\1\4\16\0"+
    "\111\4\7\15\1\4\2\15\1\4\46\15\6\0\3\4"+
    "\1\0\1\4\2\0\1\4\7\0\1\15\1\0\10\4"+
    "\12\0\6\4\6\15\1\4\2\15\1\4\40\15\5\0"+
    "\1\4\2\0\1\4\5\0\1\15\7\4\12\0\u0136\4"+
    "\23\15\4\0\11\4\2\0\1\15\1\0\15\15\1\4"+
    "\42\15\7\0\3\4\5\0\15\4\12\0\126\4\1\15"+
    "\54\4\4\15\37\4\232\15\146\4\157\15\21\4\304\15"+
    "\u014c\4\141\15\17\4\60\15\21\0\6\15\17\0\252\4"+
    "\107\15\271\4\71\15\7\4\37\15\1\4\12\0\6\4"+
    "\117\15\1\4\12\0\6\4\36\15\2\4\5\0\13\4"+
    "\60\15\7\0\11\4\4\15\14\4\12\0\11\4\25\15"+
    "\5\4\23\15\260\4\100\15\200\4\113\15\4\4\1\0"+
    "\1\15\67\0\7\4\4\0\15\15\100\4\2\15\1\4"+
    "\1\15\1\0\13\4\2\0\16\4\370\15\10\4\326\15"+
    "\52\4\11\15\u01e7\4\4\15\1\4\7\15\1\4\2\15"+
    "\1\4\43\15\17\4\1\15\35\4\3\15\2\4\1\15"+
    "\16\4\4\15\10\4\u018c\15\4\4\153\15\5\4\15\15"+
    "\3\4\11\15\7\4\12\15\3\4\2\0\1\4\4\0"+
    "\134\4\56\0\2\4\27\0\u011e\4\5\0\3\4\26\0"+
    "\2\4\7\0\36\4\4\0\224\4\3\0\273\4\125\15"+
    "\1\4\107\15\1\4\2\15\2\4\1\15\2\4\2\15"+
    "\2\4\4\15\1\4\14\15\1\4\1\15\1\4\7\15"+
    "\1\4\101\15\1\4\4\15\2\4\10\15\1\4\7\15"+
    "\1\4\34\15\1\4\4\15\1\4\5\15\1\4\1\15"+
    "\3\4\7\15\1\4\u0154\15\2\4\31\15\1\4\31\15"+
    "\1\4\37\15\1\4\31\15\1\4\37\15\1\4\31\15"+
    "\1\4\37\15\1\4\31\15\1\4\37\15\1\4\31\15"+
    "\1\4\10\15\2\4\151\0\4\4\62\0\10\4\1\0"+
    "\16\4\1\0\26\4\5\0\1\4\17\0\120\4\37\15"+
    "\6\4\6\15\325\4\7\0\1\4\21\0\2\4\7\0"+
    "\1\4\2\0\1\4\5\0\5\4\76\15\41\4\1\0"+
    "\160\4\55\15\3\4\7\0\7\15\2\4\12\0\4\4"+
    "\1\15\u0141\4\36\15\1\0\21\4\54\15\16\0\5\4"+
    "\1\15\320\4\34\15\16\0\346\4\7\15\1\4\4\15"+
    "\1\4\2\15\1\4\17\15\1\4\305\15\13\4\7\0"+
    "\51\4\104\15\7\0\1\15\4\4\12\0\u0156\4\1\15"+
    "\117\4\4\15\1\4\33\15\1\4\2\15\1\4\1\15"+
    "\2\4\1\15\1\4\12\15\1\4\4\15\1\4\1\15"+
    "\1\4\1\15\6\4\1\15\4\4\1\15\1\4\1\15"+
    "\1\4\1\15\1\4\3\15\1\4\2\15\1\4\1\15"+
    "\2\4\1\15\1\4\1\15\1\4\1\15\1\4\1\15"+
    "\1\4\1\15\1\4\2\15\1\4\1\15\2\4\4\15"+
    "\1\4\7\15\1\4\4\15\1\4\4\15\1\4\1\15"+
    "\1\4\12\15\1\4\21\15\5\4\3\15\1\4\5\15"+
    "\1\4\21\15\u0134\4\12\0\6\4\340\15\40\4\72\15"+
    "\6\4\336\15\2\4\u0182\15\16\4\u0131\15\37\4\36\15"+
    "\342\4\113\15\5\4\u0160\15\121\4\1\0\36\4\140\0"+
    "\200\4\360\0\20\4";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[32768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\11\3\1\0\1\7\2\3\1\10\1\3\1\11\4\3"+
    "\1\6\2\3\1\12\5\3\1\13\5\3\1\14\1\3"+
    "\1\15\1\3\1\16\1\17\3\3\1\20\1\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[54];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\45\0\45\0\224\0\271"+
    "\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\u01e1"+
    "\0\u0206\0\u022b\0\45\0\u0250\0\u0275\0\336\0\u029a\0\336"+
    "\0\u02bf\0\u02e4\0\u0309\0\u032e\0\u022b\0\u0353\0\u0378\0\336"+
    "\0\u039d\0\u03c2\0\u03e7\0\u040c\0\u0431\0\336\0\u0456\0\u047b"+
    "\0\u04a0\0\u04c5\0\u04ea\0\336\0\u050f\0\336\0\u0534\0\336"+
    "\0\336\0\u0559\0\u057e\0\u05a3\0\336\0\336";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[54];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\2\1\4\1\5\1\6\1\2"+
    "\1\7\1\10\1\5\12\11\1\12\1\13\1\14\1\11"+
    "\1\15\3\11\1\16\1\17\3\11\1\20\47\0\2\3"+
    "\42\0\2\11\3\0\1\11\3\0\1\11\2\0\10\11"+
    "\1\21\20\11\10\0\1\22\1\7\46\0\1\23\31\0"+
    "\2\11\3\0\1\11\3\0\1\11\2\0\33\11\3\0"+
    "\1\11\3\0\1\11\2\0\13\11\1\24\17\11\3\0"+
    "\1\11\3\0\1\11\2\0\17\11\1\25\13\11\3\0"+
    "\1\11\3\0\1\11\2\0\16\11\1\26\2\11\1\27"+
    "\11\11\3\0\1\11\3\0\1\11\2\0\14\11\1\30"+
    "\16\11\3\0\1\11\3\0\1\11\2\0\23\11\1\31"+
    "\7\11\3\0\1\11\3\0\1\11\2\0\13\11\1\32"+
    "\17\11\3\0\1\11\3\0\1\11\2\0\15\11\1\33"+
    "\15\11\3\0\1\11\3\0\1\11\2\0\7\11\1\34"+
    "\21\11\11\0\1\35\33\0\2\11\3\0\1\11\3\0"+
    "\1\11\2\0\14\11\1\36\16\11\3\0\1\11\3\0"+
    "\1\11\2\0\24\11\1\37\6\11\3\0\1\11\3\0"+
    "\1\11\2\0\23\11\1\40\7\11\3\0\1\11\3\0"+
    "\1\11\2\0\16\11\1\41\14\11\3\0\1\11\3\0"+
    "\1\11\2\0\25\11\1\42\5\11\3\0\1\11\3\0"+
    "\1\11\2\0\16\11\1\43\14\11\3\0\1\11\3\0"+
    "\1\11\2\0\1\44\32\11\3\0\1\11\3\0\1\11"+
    "\2\0\16\11\1\45\14\11\3\0\1\11\3\0\1\11"+
    "\2\0\13\11\1\46\17\11\3\0\1\11\3\0\1\11"+
    "\2\0\20\11\1\47\12\11\3\0\1\11\3\0\1\11"+
    "\2\0\26\11\1\50\4\11\3\0\1\11\3\0\1\11"+
    "\2\0\17\11\1\51\13\11\3\0\1\11\3\0\1\11"+
    "\2\0\2\11\1\52\30\11\3\0\1\11\3\0\1\11"+
    "\2\0\20\11\1\53\12\11\3\0\1\11\3\0\1\11"+
    "\2\0\25\11\1\54\5\11\3\0\1\11\3\0\1\11"+
    "\2\0\23\11\1\55\7\11\3\0\1\11\3\0\1\11"+
    "\2\0\13\11\1\56\17\11\3\0\1\11\3\0\1\11"+
    "\2\0\3\11\1\57\27\11\3\0\1\11\3\0\1\11"+
    "\2\0\13\11\1\60\17\11\3\0\1\11\3\0\1\11"+
    "\2\0\20\11\1\61\12\11\3\0\1\11\3\0\1\11"+
    "\2\0\11\11\1\62\21\11\3\0\1\11\3\0\1\11"+
    "\2\0\6\11\1\63\24\11\3\0\1\11\3\0\1\11"+
    "\2\0\4\11\1\64\1\65\25\11\3\0\1\11\3\0"+
    "\1\11\2\0\4\11\1\66\24\11";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1480];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\2\11\13\1\1\0\1\11\43\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[54];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private AsdrSample yyparser;

  public Yylex(java.io.Reader r, AsdrSample yyparser) {
    this(r);
    this.yyparser = yyparser;
  }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Erro lexico: caracter invalido: <" + yytext() + ">");
            }
          // fall through
          case 18: break;
          case 2:
            { 
            }
          // fall through
          case 19: break;
          case 3:
            { return AsdrSample.IDENT;
            }
          // fall through
          case 20: break;
          case 4:
            { return yytext().charAt(0);
            }
          // fall through
          case 21: break;
          case 5:
            { return AsdrSample.OP;
            }
          // fall through
          case 22: break;
          case 6:
            { return AsdrSample.NUM;
            }
          // fall through
          case 23: break;
          case 7:
            { return AsdrSample.LE;
            }
          // fall through
          case 24: break;
          case 8:
            { return AsdrSample.FI;
            }
          // fall through
          case 25: break;
          case 9:
            { return AsdrSample.IF;
            }
          // fall through
          case 26: break;
          case 10:
            { return AsdrSample.FOR;
            }
          // fall through
          case 27: break;
          case 11:
            { return AsdrSample.ELSE;
            }
          // fall through
          case 28: break;
          case 12:
            { return AsdrSample.PRINT;
            }
          // fall through
          case 29: break;
          case 13:
            { return AsdrSample.WHILE;
            }
          // fall through
          case 30: break;
          case 14:
            { return AsdrSample.DEFINE;
            }
          // fall through
          case 31: break;
          case 15:
            { return AsdrSample.RETURN;
            }
          // fall through
          case 32: break;
          case 16:
            { yyparser.setDebug(true);
            }
          // fall through
          case 33: break;
          case 17:
            { yyparser.setDebug(false);
            }
          // fall through
          case 34: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
